version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:9.5.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=quizquestions
    ports:
      - "5432:5432"
    volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
